import "./globals.css";
import { IsLoggedProvider } from "@/Context/IsloggedContext";
import LayoutWrapper from "@/Components/LayoutWrapper";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <IsLoggedProvider>
          <LayoutWrapper>
            {children}
            <div className="absolute inset-0 -z-10 h-full w-full bg-white [background:radial-gradient(125%_125%_at_50%_10%,#fff_40%,#63e_100%)]">
            </div>
          </LayoutWrapper>
        </IsLoggedProvider>
      </body>
    </html>
  );
}
